# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kondooruk3@gmail.com
author_name: KrishnakumarKPK
contract_name: msme
deployment_language: python
preset_name: production
project_name: MSME-contracts

