# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: kondooruk3@gmail.com
author_name: KrishnakumarKPK
cloud_provider: netlify
contract_name: msme
deployment_language: python
preset_name: production
project_name: MSME

